"""add verified_total_marks to certificates

Revision ID: 9f4c0b5ae76d
Revises: 794193fcc1f0
Create Date: 2025-05-23 19:46:50.834360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4c0b5ae76d'
down_revision: Union[str, None] = '794193fcc1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('verified_total_marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'verified_total_marks')
    # ### end Alembic commands ###
